### ISSUE TITLE
Better Links on Flathub

### ISSUE THREAD

**Issue by DominiqueSite** [flathub/org.gnunet.Messenger#1]
Flathub allows for Applications to link to e.g. their website, their donation page, their support page, their bug tracker and their localization platform (examples taken from [here](https://flathub.org/apps/details/org.mozilla.firefox)).
For Messenger-GTK, the only link currently displayed is "Website"; this links to the main site of GNUnet, gnunet.org. I propose to link to the [readme.md](https://git.gnunet.org/messenger-gtk.git/tree/README.md) at git.gnunet.org instead.
For "Issues", the right bug tracker is currently at [bugs.gnunet.org](https://bugs.gnunet.org/my_view_page.php). For people who want to fund development, the best way would probably be to donate to @TheJackiMonster via [Liberapay](https://liberapay.com/TheJackiMonster/) or to GNUnet e.V. via [bank transfer or Bitcoin](https://www.gnunet.org/en/ev.html).

**Comment by hfiguiere** [comment]
Given that this is managed through the appstream file and the appstream file come from upstream, this is an upstream  issue....

**Comment by TheJackiMonster** [comment]
I will take care of this (the file is [here](https://git.gnunet.org/messenger-gtk.git/tree/resources/org.gnunet.Messenger.appdata.xml)). So the next release should have the required information.
